# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2276958537647e04a1acb094f213658add1d0c400d802aa78a2879822f6416df11224b1a76e0bcd259b63b63e69ae42f84a2da2673402fbffe17d0f8bf28438d

test:
  secret_key_base: f788a5652aaee4675851f7010229f460d6ddf8f8705511a54b51eb120fdc5a9933fe18cd923651fe034780843f97e578c4114916f00b8906356552ac0eccf22c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
